name: vpay
description: vPay Flutter application
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.1
  flutter_riverpod: ^2.4.9
  go_router: ^13.1.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  google_maps_flutter: ^2.5.3
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_chat_ui: ^1.6.12
  cupertino_icons: ^1.0.8
  upi_india: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/eye_password.png
    - assets/images/facebook logo.png
    - assets/images/google logo.png
    - assets/images/logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
