// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdnKwVf8l0KKBR5MyeIixfR7a6nCn4FAQ',
    appId: '1:371562210642:web:53cc78b138f2466235868b',
    messagingSenderId: '371562210642',
    projectId: 'vpay-7',
    authDomain: 'vpay-7.firebaseapp.com',
    storageBucket: 'vpay-7.firebasestorage.app',
    measurementId: 'G-7CQDLHSSVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9L8pn_1XfNu0iOvioOqHcnlYJtCHWYwQ',
    appId: '1:371562210642:android:3a546f4125c7a37a35868b',
    messagingSenderId: '371562210642',
    projectId: 'vpay-7',
    storageBucket: 'vpay-7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvxMbWUDJYRHreoNXU2Q4c5yagwIIRRP4',
    appId: '1:371562210642:ios:ece665fe4f15994435868b',
    messagingSenderId: '371562210642',
    projectId: 'vpay-7',
    storageBucket: 'vpay-7.firebasestorage.app',
    iosBundleId: 'dev.vpay.vpayFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvxMbWUDJYRHreoNXU2Q4c5yagwIIRRP4',
    appId: '1:371562210642:ios:ece665fe4f15994435868b',
    messagingSenderId: '371562210642',
    projectId: 'vpay-7',
    storageBucket: 'vpay-7.firebasestorage.app',
    iosBundleId: 'dev.vpay.vpayFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdnKwVf8l0KKBR5MyeIixfR7a6nCn4FAQ',
    appId: '1:371562210642:web:dcaa5bb50e3b53cd35868b',
    messagingSenderId: '371562210642',
    projectId: 'vpay-7',
    authDomain: 'vpay-7.firebaseapp.com',
    storageBucket: 'vpay-7.firebasestorage.app',
    measurementId: 'G-LDR0S9DQY7',
  );
}
